name: pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: UseNode
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.12.0

      # - name: UsePNPM
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 9
      #     run_install: false

      # - name: Build
      #   run: |
      #     pnpm install
      #     pnpm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: 'dist'
